# Generated by Django 2.2.7 on 2020-01-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='file1',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='message',
            name='file1',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
