# Generated by Django 2.2.7 on 2020-02-03 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20200104_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id_issue',
            new_name='issue',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='date_change',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='date_open',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_post',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image3',
        ),
        migrations.AddField(
            model_name='issue',
            name='file2',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='issue',
            name='file3',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='issue',
            name='time_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='time_open',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='file2',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='message',
            name='file3',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='time_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Открыта'), (1, 'Закрыта')], default=0),
        ),
    ]
