# Generated by Django 2.2.7 on 2019-12-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('portfolio', models.CharField(choices=[('DEMO', 'Демография'), ('ZDRV', 'Здравоохранение'), ('OBR', 'Образование'), ('ZGS', 'Жилье и городская среда'), ('BKAD', 'Безопасные и качественные автомобильные дороги'), ('CIF', 'Цифровая экономика'), ('MEZD', 'Международная кооперация и экспорт'), ('TRUD', 'Производительность труда и поддержка занятости'), ('MSP', 'Малое и среднее предпринимательство'), ('ECO', 'Экология'), ('CULT', 'Культура')], max_length=4)),
                ('code', models.CharField(max_length=3)),
                ('id_director', models.IntegerField()),
                ('id_administrator', models.IntegerField()),
                ('id_curator', models.IntegerField()),
                ('id_mentor', models.IntegerField()),
                ('id_support', models.IntegerField()),
                ('id_worker', models.IntegerField()),
                ('date_pasport', models.DateField()),
                ('need_update', models.IntegerField(choices=[('0', 'Нет'), ('1', 'Да'), ('2', 'Необходимо уточнение')], max_length=1)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
