# Generated by Django 2.2.7 on 2019-12-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191211_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=255)),
                ('fio_full', models.CharField(blank=True, max_length=255)),
                ('job', models.CharField(blank=True, max_length=255)),
                ('post', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('tell', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_pasport',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id_administrator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id_curator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id_director',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id_mentor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id_support',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id_worker',
        ),
        migrations.RemoveField(
            model_name='project',
            name='need_update',
        ),
        migrations.AddField(
            model_name='project',
            name='administrator',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='critical_error',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='curator',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='date_change_status',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
