# Generated by Django 2.2.7 on 2019-12-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191221_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='fio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='fio_full',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='job',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='post',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='administrator',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='critical_error',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='curator',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_change_status',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.CharField(max_length=4),
        ),
    ]
