# Generated by Django 2.2.7 on 2019-12-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20191221_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fio_full',
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='post',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='tell',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='administrator',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='critical_error',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='curator',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_change_status',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')])),
                ('year', models.IntegerField(blank=True, choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')])),
                ('file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('approval', models.IntegerField(blank=True, choices=[('1', 'Да'), ('2', 'Нет'), ('3', 'Неизвестно')])),
                ('expired', models.IntegerField(blank=True, choices=[('1', 'Да'), ('2', 'Нет'), ('3', 'Неизвестно')])),
                ('correct', models.IntegerField(blank=True, choices=[('1', 'Да'), ('2', 'Нет'), ('3', 'Неизвестно')])),
                ('sending_date', models.DateField(blank=True)),
                ('approval_date', models.DateField(blank=True)),
                ('date_change_status', models.DateField(blank=True)),
                ('project', models.ForeignKey(on_delete=models.SET('проект удален'), to='project.Project')),
            ],
        ),
    ]
