# Generated by Django 2.2.7 on 2019-12-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20191227_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tell',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='approval',
            field=models.IntegerField(blank=True, choices=[(1, 'Да'), (2, 'Нет'), (3, 'Неизвестно')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct',
            field=models.IntegerField(blank=True, choices=[(1, 'Да'), (2, 'Нет'), (3, 'Неизвестно')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='expired',
            field=models.IntegerField(blank=True, choices=[(1, 'Да'), (2, 'Нет'), (3, 'Неизвестно')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')]),
        ),
    ]
