# Generated by Django 2.2.7 on 2020-01-04 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_report_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_post', models.DateField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='screens/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='screens/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='screens/%Y/%m/%d')),
                ('file1', models.FileField(blank=True, upload_to='files/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=models.SET('пользователь удален'), to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=models.SET('проект удален'), to='project.Project')),
            ],
        ),
    ]
