# Generated by Django 2.2.7 on 2020-02-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='comment',
            new_name='director',
        ),
        migrations.RemoveField(
            model_name='project',
            name='critical_error',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_change_status',
        ),
        migrations.AddField(
            model_name='project',
            name='bad_finance',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='need_sogl',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='need_zi',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='time_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='administrator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='curator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
