# Generated by Django 2.2.7 on 2020-02-07 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200206_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='date_post',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='report',
            name='date_change_status',
        ),
        migrations.RemoveField(
            model_name='report',
            name='sending_date',
        ),
        migrations.AddField(
            model_name='chat',
            name='file2',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='chat',
            name='file3',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='time_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='time_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='approval',
            field=models.IntegerField(blank=True, choices=[(1, 'Да'), (0, 'Нет')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct',
            field=models.IntegerField(blank=True, choices=[(1, 'Да'), (0, 'Нет')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='expired',
            field=models.IntegerField(blank=True, choices=[(1, 'Да'), (0, 'Нет')]),
        ),
    ]
